// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: apple_wps.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ALSLocationRequest_WifiBand int32

const (
	ALSLocationRequest_WIFI_BAND_UNKNOWN ALSLocationRequest_WifiBand = 0
	ALSLocationRequest_K2DOT4GHZ         ALSLocationRequest_WifiBand = 1
	ALSLocationRequest_K5GHZ             ALSLocationRequest_WifiBand = 2
)

// Enum value maps for ALSLocationRequest_WifiBand.
var (
	ALSLocationRequest_WifiBand_name = map[int32]string{
		0: "WIFI_BAND_UNKNOWN",
		1: "K2DOT4GHZ",
		2: "K5GHZ",
	}
	ALSLocationRequest_WifiBand_value = map[string]int32{
		"WIFI_BAND_UNKNOWN": 0,
		"K2DOT4GHZ":         1,
		"K5GHZ":             2,
	}
)

func (x ALSLocationRequest_WifiBand) Enum() *ALSLocationRequest_WifiBand {
	p := new(ALSLocationRequest_WifiBand)
	*p = x
	return p
}

func (x ALSLocationRequest_WifiBand) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ALSLocationRequest_WifiBand) Descriptor() protoreflect.EnumDescriptor {
	return file_apple_wps_proto_enumTypes[0].Descriptor()
}

func (ALSLocationRequest_WifiBand) Type() protoreflect.EnumType {
	return &file_apple_wps_proto_enumTypes[0]
}

func (x ALSLocationRequest_WifiBand) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ALSLocationRequest_WifiBand.Descriptor instead.
func (ALSLocationRequest_WifiBand) EnumDescriptor() ([]byte, []int) {
	return file_apple_wps_proto_rawDescGZIP(), []int{0, 0}
}

type ALSLocationRequest_WifiAltitudeScale int32

const (
	ALSLocationRequest_WIFI_ALTITUDE_SCALE_UNKNOWN      ALSLocationRequest_WifiAltitudeScale = 0
	ALSLocationRequest_KWIFI_ALTITUDE_SCALE_NONE        ALSLocationRequest_WifiAltitudeScale = 1
	ALSLocationRequest_KWIFI_ALTITUDE_SCALE_10_TO_THE_2 ALSLocationRequest_WifiAltitudeScale = 2
)

// Enum value maps for ALSLocationRequest_WifiAltitudeScale.
var (
	ALSLocationRequest_WifiAltitudeScale_name = map[int32]string{
		0: "WIFI_ALTITUDE_SCALE_UNKNOWN",
		1: "KWIFI_ALTITUDE_SCALE_NONE",
		2: "KWIFI_ALTITUDE_SCALE_10_TO_THE_2",
	}
	ALSLocationRequest_WifiAltitudeScale_value = map[string]int32{
		"WIFI_ALTITUDE_SCALE_UNKNOWN":      0,
		"KWIFI_ALTITUDE_SCALE_NONE":        1,
		"KWIFI_ALTITUDE_SCALE_10_TO_THE_2": 2,
	}
)

func (x ALSLocationRequest_WifiAltitudeScale) Enum() *ALSLocationRequest_WifiAltitudeScale {
	p := new(ALSLocationRequest_WifiAltitudeScale)
	*p = x
	return p
}

func (x ALSLocationRequest_WifiAltitudeScale) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ALSLocationRequest_WifiAltitudeScale) Descriptor() protoreflect.EnumDescriptor {
	return file_apple_wps_proto_enumTypes[1].Descriptor()
}

func (ALSLocationRequest_WifiAltitudeScale) Type() protoreflect.EnumType {
	return &file_apple_wps_proto_enumTypes[1]
}

func (x ALSLocationRequest_WifiAltitudeScale) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ALSLocationRequest_WifiAltitudeScale.Descriptor instead.
func (ALSLocationRequest_WifiAltitudeScale) EnumDescriptor() ([]byte, []int) {
	return file_apple_wps_proto_rawDescGZIP(), []int{0, 1}
}

type ALSLocationRequest struct {
	state                            protoimpl.MessageState                `protogen:"open.v1"`
	CellTowers                       []*CellTower                          `protobuf:"bytes,1,rep,name=cell_towers,json=cellTowers,proto3" json:"cell_towers,omitempty"`
	WirelessAps                      []*WirelessAP                         `protobuf:"bytes,2,rep,name=wireless_aps,json=wirelessAps,proto3" json:"wireless_aps,omitempty"`
	NumberOfSurroundingCells         *int32                                `protobuf:"varint,3,opt,name=number_of_surrounding_cells,json=numberOfSurroundingCells,proto3,oneof" json:"number_of_surrounding_cells,omitempty"`
	NumberOfSurroundingWifis         *int32                                `protobuf:"varint,4,opt,name=number_of_surrounding_wifis,json=numberOfSurroundingWifis,proto3,oneof" json:"number_of_surrounding_wifis,omitempty"`
	AppBundleId                      *string                               `protobuf:"bytes,5,opt,name=app_bundle_id,json=appBundleId,proto3,oneof" json:"app_bundle_id,omitempty"`
	CdmaCellTowers                   []*CdmaCellTower                      `protobuf:"bytes,21,rep,name=cdma_cell_towers,json=cdmaCellTowers,proto3" json:"cdma_cell_towers,omitempty"`
	CdmaEvdoTowers                   []*CdmaEvdoTower                      `protobuf:"bytes,22,rep,name=cdma_evdo_towers,json=cdmaEvdoTowers,proto3" json:"cdma_evdo_towers,omitempty"`
	NumberOfSurroundingCdmaCells     *int32                                `protobuf:"varint,23,opt,name=number_of_surrounding_cdma_cells,json=numberOfSurroundingCdmaCells,proto3,oneof" json:"number_of_surrounding_cdma_cells,omitempty"`
	NumberOfSurroundingCdmaEvdoCells *int32                                `protobuf:"varint,24,opt,name=number_of_surrounding_cdma_evdo_cells,json=numberOfSurroundingCdmaEvdoCells,proto3,oneof" json:"number_of_surrounding_cdma_evdo_cells,omitempty"`
	LteCellTowers                    []*LteCellTower                       `protobuf:"bytes,25,rep,name=lte_cell_towers,json=lteCellTowers,proto3" json:"lte_cell_towers,omitempty"`
	NumberOfSurroundingLteCells      *int32                                `protobuf:"varint,26,opt,name=number_of_surrounding_lte_cells,json=numberOfSurroundingLteCells,proto3,oneof" json:"number_of_surrounding_lte_cells,omitempty"`
	ScdmaCellTowers                  []*ScdmaCellTower                     `protobuf:"bytes,27,rep,name=scdma_cell_towers,json=scdmaCellTowers,proto3" json:"scdma_cell_towers,omitempty"`
	NumberOfSurroundingScdmaCells    *int32                                `protobuf:"varint,28,opt,name=number_of_surrounding_scdma_cells,json=numberOfSurroundingScdmaCells,proto3,oneof" json:"number_of_surrounding_scdma_cells,omitempty"`
	Nr5GCellTowers                   []*Nr5GCellTower                      `protobuf:"bytes,29,rep,name=nr5g_cell_towers,json=nr5gCellTowers,proto3" json:"nr5g_cell_towers,omitempty"`
	NumberOfSurroundingNr5GCells     *int32                                `protobuf:"varint,30,opt,name=number_of_surrounding_nr5g_cells,json=numberOfSurroundingNr5gCells,proto3,oneof" json:"number_of_surrounding_nr5g_cells,omitempty"`
	SurroundingWifiBands             []ALSLocationRequest_WifiBand         `protobuf:"varint,31,rep,packed,name=surrounding_wifi_bands,json=surroundingWifiBands,proto3,enum=ALSLocationRequest_WifiBand" json:"surrounding_wifi_bands,omitempty"`
	WifiAltitudeScale                *ALSLocationRequest_WifiAltitudeScale `protobuf:"varint,32,opt,name=wifi_altitude_scale,json=wifiAltitudeScale,proto3,enum=ALSLocationRequest_WifiAltitudeScale,oneof" json:"wifi_altitude_scale,omitempty"`
	Meta                             *ALSLocationRequest_ALSMeta           `protobuf:"bytes,33,opt,name=meta,proto3,oneof" json:"meta,omitempty"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *ALSLocationRequest) Reset() {
	*x = ALSLocationRequest{}
	mi := &file_apple_wps_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ALSLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ALSLocationRequest) ProtoMessage() {}

func (x *ALSLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apple_wps_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ALSLocationRequest.ProtoReflect.Descriptor instead.
func (*ALSLocationRequest) Descriptor() ([]byte, []int) {
	return file_apple_wps_proto_rawDescGZIP(), []int{0}
}

func (x *ALSLocationRequest) GetCellTowers() []*CellTower {
	if x != nil {
		return x.CellTowers
	}
	return nil
}

func (x *ALSLocationRequest) GetWirelessAps() []*WirelessAP {
	if x != nil {
		return x.WirelessAps
	}
	return nil
}

func (x *ALSLocationRequest) GetNumberOfSurroundingCells() int32 {
	if x != nil && x.NumberOfSurroundingCells != nil {
		return *x.NumberOfSurroundingCells
	}
	return 0
}

func (x *ALSLocationRequest) GetNumberOfSurroundingWifis() int32 {
	if x != nil && x.NumberOfSurroundingWifis != nil {
		return *x.NumberOfSurroundingWifis
	}
	return 0
}

func (x *ALSLocationRequest) GetAppBundleId() string {
	if x != nil && x.AppBundleId != nil {
		return *x.AppBundleId
	}
	return ""
}

func (x *ALSLocationRequest) GetCdmaCellTowers() []*CdmaCellTower {
	if x != nil {
		return x.CdmaCellTowers
	}
	return nil
}

func (x *ALSLocationRequest) GetCdmaEvdoTowers() []*CdmaEvdoTower {
	if x != nil {
		return x.CdmaEvdoTowers
	}
	return nil
}

func (x *ALSLocationRequest) GetNumberOfSurroundingCdmaCells() int32 {
	if x != nil && x.NumberOfSurroundingCdmaCells != nil {
		return *x.NumberOfSurroundingCdmaCells
	}
	return 0
}

func (x *ALSLocationRequest) GetNumberOfSurroundingCdmaEvdoCells() int32 {
	if x != nil && x.NumberOfSurroundingCdmaEvdoCells != nil {
		return *x.NumberOfSurroundingCdmaEvdoCells
	}
	return 0
}

func (x *ALSLocationRequest) GetLteCellTowers() []*LteCellTower {
	if x != nil {
		return x.LteCellTowers
	}
	return nil
}

func (x *ALSLocationRequest) GetNumberOfSurroundingLteCells() int32 {
	if x != nil && x.NumberOfSurroundingLteCells != nil {
		return *x.NumberOfSurroundingLteCells
	}
	return 0
}

func (x *ALSLocationRequest) GetScdmaCellTowers() []*ScdmaCellTower {
	if x != nil {
		return x.ScdmaCellTowers
	}
	return nil
}

func (x *ALSLocationRequest) GetNumberOfSurroundingScdmaCells() int32 {
	if x != nil && x.NumberOfSurroundingScdmaCells != nil {
		return *x.NumberOfSurroundingScdmaCells
	}
	return 0
}

func (x *ALSLocationRequest) GetNr5GCellTowers() []*Nr5GCellTower {
	if x != nil {
		return x.Nr5GCellTowers
	}
	return nil
}

func (x *ALSLocationRequest) GetNumberOfSurroundingNr5GCells() int32 {
	if x != nil && x.NumberOfSurroundingNr5GCells != nil {
		return *x.NumberOfSurroundingNr5GCells
	}
	return 0
}

func (x *ALSLocationRequest) GetSurroundingWifiBands() []ALSLocationRequest_WifiBand {
	if x != nil {
		return x.SurroundingWifiBands
	}
	return nil
}

func (x *ALSLocationRequest) GetWifiAltitudeScale() ALSLocationRequest_WifiAltitudeScale {
	if x != nil && x.WifiAltitudeScale != nil {
		return *x.WifiAltitudeScale
	}
	return ALSLocationRequest_WIFI_ALTITUDE_SCALE_UNKNOWN
}

func (x *ALSLocationRequest) GetMeta() *ALSLocationRequest_ALSMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type ALSLocationResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CellTowers      []*CellTower           `protobuf:"bytes,1,rep,name=cell_towers,json=cellTowers,proto3" json:"cell_towers,omitempty"`
	WirelessAps     []*WirelessAP          `protobuf:"bytes,2,rep,name=wireless_aps,json=wirelessAps,proto3" json:"wireless_aps,omitempty"`
	CdmaCellTowers  []*CdmaCellTower       `protobuf:"bytes,21,rep,name=cdma_cell_towers,json=cdmaCellTowers,proto3" json:"cdma_cell_towers,omitempty"`
	LteCellTowers   []*LteCellTower        `protobuf:"bytes,22,rep,name=lte_cell_towers,json=lteCellTowers,proto3" json:"lte_cell_towers,omitempty"`
	ScdmaCellTowers []*ScdmaCellTower      `protobuf:"bytes,23,rep,name=scdma_cell_towers,json=scdmaCellTowers,proto3" json:"scdma_cell_towers,omitempty"`
	Nr5GCellTowers  []*Nr5GCellTower       `protobuf:"bytes,24,rep,name=nr5g_cell_towers,json=nr5gCellTowers,proto3" json:"nr5g_cell_towers,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ALSLocationResponse) Reset() {
	*x = ALSLocationResponse{}
	mi := &file_apple_wps_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ALSLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ALSLocationResponse) ProtoMessage() {}

func (x *ALSLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apple_wps_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ALSLocationResponse.ProtoReflect.Descriptor instead.
func (*ALSLocationResponse) Descriptor() ([]byte, []int) {
	return file_apple_wps_proto_rawDescGZIP(), []int{1}
}

func (x *ALSLocationResponse) GetCellTowers() []*CellTower {
	if x != nil {
		return x.CellTowers
	}
	return nil
}

func (x *ALSLocationResponse) GetWirelessAps() []*WirelessAP {
	if x != nil {
		return x.WirelessAps
	}
	return nil
}

func (x *ALSLocationResponse) GetCdmaCellTowers() []*CdmaCellTower {
	if x != nil {
		return x.CdmaCellTowers
	}
	return nil
}

func (x *ALSLocationResponse) GetLteCellTowers() []*LteCellTower {
	if x != nil {
		return x.LteCellTowers
	}
	return nil
}

func (x *ALSLocationResponse) GetScdmaCellTowers() []*ScdmaCellTower {
	if x != nil {
		return x.ScdmaCellTowers
	}
	return nil
}

func (x *ALSLocationResponse) GetNr5GCellTowers() []*Nr5GCellTower {
	if x != nil {
		return x.Nr5GCellTowers
	}
	return nil
}

type ALSLocation struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Latitude         int64                  `protobuf:"varint,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude        int64                  `protobuf:"varint,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Accuracy         int32                  `protobuf:"varint,3,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	LocationType     *int32                 `protobuf:"varint,4,opt,name=location_type,json=locationType,proto3,oneof" json:"location_type,omitempty"`
	Altitude         *int32                 `protobuf:"varint,5,opt,name=altitude,proto3,oneof" json:"altitude,omitempty"`
	VerticalAccuracy *int32                 `protobuf:"varint,6,opt,name=vertical_accuracy,json=verticalAccuracy,proto3,oneof" json:"vertical_accuracy,omitempty"`
	Confidence       *int32                 `protobuf:"varint,7,opt,name=confidence,proto3,oneof" json:"confidence,omitempty"`
	Score            *uint32                `protobuf:"varint,11,opt,name=score,proto3,oneof" json:"score,omitempty"`
	Reach            *int32                 `protobuf:"varint,12,opt,name=reach,proto3,oneof" json:"reach,omitempty"`
	InfoMask         *uint32                `protobuf:"varint,13,opt,name=info_mask,json=infoMask,proto3,oneof" json:"info_mask,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ALSLocation) Reset() {
	*x = ALSLocation{}
	mi := &file_apple_wps_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ALSLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ALSLocation) ProtoMessage() {}

func (x *ALSLocation) ProtoReflect() protoreflect.Message {
	mi := &file_apple_wps_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ALSLocation.ProtoReflect.Descriptor instead.
func (*ALSLocation) Descriptor() ([]byte, []int) {
	return file_apple_wps_proto_rawDescGZIP(), []int{2}
}

func (x *ALSLocation) GetLatitude() int64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *ALSLocation) GetLongitude() int64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *ALSLocation) GetAccuracy() int32 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

func (x *ALSLocation) GetLocationType() int32 {
	if x != nil && x.LocationType != nil {
		return *x.LocationType
	}
	return 0
}

func (x *ALSLocation) GetAltitude() int32 {
	if x != nil && x.Altitude != nil {
		return *x.Altitude
	}
	return 0
}

func (x *ALSLocation) GetVerticalAccuracy() int32 {
	if x != nil && x.VerticalAccuracy != nil {
		return *x.VerticalAccuracy
	}
	return 0
}

func (x *ALSLocation) GetConfidence() int32 {
	if x != nil && x.Confidence != nil {
		return *x.Confidence
	}
	return 0
}

func (x *ALSLocation) GetScore() uint32 {
	if x != nil && x.Score != nil {
		return *x.Score
	}
	return 0
}

func (x *ALSLocation) GetReach() int32 {
	if x != nil && x.Reach != nil {
		return *x.Reach
	}
	return 0
}

func (x *ALSLocation) GetInfoMask() uint32 {
	if x != nil && x.InfoMask != nil {
		return *x.InfoMask
	}
	return 0
}

type CellTower struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mcc           int32                  `protobuf:"varint,1,opt,name=mcc,proto3" json:"mcc,omitempty"`
	Mnc           int32                  `protobuf:"varint,2,opt,name=mnc,proto3" json:"mnc,omitempty"`
	CellId        int32                  `protobuf:"varint,3,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
	LacId         int32                  `protobuf:"varint,4,opt,name=lac_id,json=lacId,proto3" json:"lac_id,omitempty"`
	Location      *ALSLocation           `protobuf:"bytes,5,opt,name=location,proto3,oneof" json:"location,omitempty"`
	Arcfn         *int32                 `protobuf:"varint,11,opt,name=arcfn,proto3,oneof" json:"arcfn,omitempty"`
	Psc           *int32                 `protobuf:"varint,12,opt,name=psc,proto3,oneof" json:"psc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CellTower) Reset() {
	*x = CellTower{}
	mi := &file_apple_wps_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CellTower) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellTower) ProtoMessage() {}

func (x *CellTower) ProtoReflect() protoreflect.Message {
	mi := &file_apple_wps_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellTower.ProtoReflect.Descriptor instead.
func (*CellTower) Descriptor() ([]byte, []int) {
	return file_apple_wps_proto_rawDescGZIP(), []int{3}
}

func (x *CellTower) GetMcc() int32 {
	if x != nil {
		return x.Mcc
	}
	return 0
}

func (x *CellTower) GetMnc() int32 {
	if x != nil {
		return x.Mnc
	}
	return 0
}

func (x *CellTower) GetCellId() int32 {
	if x != nil {
		return x.CellId
	}
	return 0
}

func (x *CellTower) GetLacId() int32 {
	if x != nil {
		return x.LacId
	}
	return 0
}

func (x *CellTower) GetLocation() *ALSLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *CellTower) GetArcfn() int32 {
	if x != nil && x.Arcfn != nil {
		return *x.Arcfn
	}
	return 0
}

func (x *CellTower) GetPsc() int32 {
	if x != nil && x.Psc != nil {
		return *x.Psc
	}
	return 0
}

type WirelessAP struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	MacId                 string                 `protobuf:"bytes,1,opt,name=mac_id,json=macId,proto3" json:"mac_id,omitempty"`
	Location              *ALSLocation           `protobuf:"bytes,2,opt,name=location,proto3,oneof" json:"location,omitempty"`
	Channel               *uint32                `protobuf:"varint,21,opt,name=channel,proto3,oneof" json:"channel,omitempty"`
	NumZaxisHarvestTraces *uint32                `protobuf:"varint,22,opt,name=num_zaxis_harvest_traces,json=numZaxisHarvestTraces,proto3,oneof" json:"num_zaxis_harvest_traces,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *WirelessAP) Reset() {
	*x = WirelessAP{}
	mi := &file_apple_wps_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WirelessAP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WirelessAP) ProtoMessage() {}

func (x *WirelessAP) ProtoReflect() protoreflect.Message {
	mi := &file_apple_wps_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WirelessAP.ProtoReflect.Descriptor instead.
func (*WirelessAP) Descriptor() ([]byte, []int) {
	return file_apple_wps_proto_rawDescGZIP(), []int{4}
}

func (x *WirelessAP) GetMacId() string {
	if x != nil {
		return x.MacId
	}
	return ""
}

func (x *WirelessAP) GetLocation() *ALSLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *WirelessAP) GetChannel() uint32 {
	if x != nil && x.Channel != nil {
		return *x.Channel
	}
	return 0
}

func (x *WirelessAP) GetNumZaxisHarvestTraces() uint32 {
	if x != nil && x.NumZaxisHarvestTraces != nil {
		return *x.NumZaxisHarvestTraces
	}
	return 0
}

type CdmaCellTower struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mcc           *int32                 `protobuf:"varint,1,opt,name=mcc,proto3,oneof" json:"mcc,omitempty"`
	Sid           *int32                 `protobuf:"varint,3,opt,name=sid,proto3,oneof" json:"sid,omitempty"`
	Nid           *int32                 `protobuf:"varint,4,opt,name=nid,proto3,oneof" json:"nid,omitempty"`
	Bsid          *int32                 `protobuf:"varint,5,opt,name=bsid,proto3,oneof" json:"bsid,omitempty"`
	Location      *ALSLocation           `protobuf:"bytes,6,opt,name=location,proto3,oneof" json:"location,omitempty"`
	Zoneid        *int32                 `protobuf:"varint,7,opt,name=zoneid,proto3,oneof" json:"zoneid,omitempty"`
	Bandclass     *int32                 `protobuf:"varint,8,opt,name=bandclass,proto3,oneof" json:"bandclass,omitempty"`
	Channel       *int32                 `protobuf:"varint,9,opt,name=channel,proto3,oneof" json:"channel,omitempty"`
	Pnoffset      *int32                 `protobuf:"varint,10,opt,name=pnoffset,proto3,oneof" json:"pnoffset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CdmaCellTower) Reset() {
	*x = CdmaCellTower{}
	mi := &file_apple_wps_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CdmaCellTower) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CdmaCellTower) ProtoMessage() {}

func (x *CdmaCellTower) ProtoReflect() protoreflect.Message {
	mi := &file_apple_wps_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CdmaCellTower.ProtoReflect.Descriptor instead.
func (*CdmaCellTower) Descriptor() ([]byte, []int) {
	return file_apple_wps_proto_rawDescGZIP(), []int{5}
}

func (x *CdmaCellTower) GetMcc() int32 {
	if x != nil && x.Mcc != nil {
		return *x.Mcc
	}
	return 0
}

func (x *CdmaCellTower) GetSid() int32 {
	if x != nil && x.Sid != nil {
		return *x.Sid
	}
	return 0
}

func (x *CdmaCellTower) GetNid() int32 {
	if x != nil && x.Nid != nil {
		return *x.Nid
	}
	return 0
}

func (x *CdmaCellTower) GetBsid() int32 {
	if x != nil && x.Bsid != nil {
		return *x.Bsid
	}
	return 0
}

func (x *CdmaCellTower) GetLocation() *ALSLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *CdmaCellTower) GetZoneid() int32 {
	if x != nil && x.Zoneid != nil {
		return *x.Zoneid
	}
	return 0
}

func (x *CdmaCellTower) GetBandclass() int32 {
	if x != nil && x.Bandclass != nil {
		return *x.Bandclass
	}
	return 0
}

func (x *CdmaCellTower) GetChannel() int32 {
	if x != nil && x.Channel != nil {
		return *x.Channel
	}
	return 0
}

func (x *CdmaCellTower) GetPnoffset() int32 {
	if x != nil && x.Pnoffset != nil {
		return *x.Pnoffset
	}
	return 0
}

type CdmaEvdoTower struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sectorid      string                 `protobuf:"bytes,1,opt,name=sectorid,proto3" json:"sectorid,omitempty"`
	Bandclass     *int32                 `protobuf:"varint,2,opt,name=bandclass,proto3,oneof" json:"bandclass,omitempty"`
	Channel       *int32                 `protobuf:"varint,3,opt,name=channel,proto3,oneof" json:"channel,omitempty"`
	Pnoffset      *int32                 `protobuf:"varint,4,opt,name=pnoffset,proto3,oneof" json:"pnoffset,omitempty"`
	Location      *ALSLocation           `protobuf:"bytes,5,opt,name=location,proto3,oneof" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CdmaEvdoTower) Reset() {
	*x = CdmaEvdoTower{}
	mi := &file_apple_wps_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CdmaEvdoTower) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CdmaEvdoTower) ProtoMessage() {}

func (x *CdmaEvdoTower) ProtoReflect() protoreflect.Message {
	mi := &file_apple_wps_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CdmaEvdoTower.ProtoReflect.Descriptor instead.
func (*CdmaEvdoTower) Descriptor() ([]byte, []int) {
	return file_apple_wps_proto_rawDescGZIP(), []int{6}
}

func (x *CdmaEvdoTower) GetSectorid() string {
	if x != nil {
		return x.Sectorid
	}
	return ""
}

func (x *CdmaEvdoTower) GetBandclass() int32 {
	if x != nil && x.Bandclass != nil {
		return *x.Bandclass
	}
	return 0
}

func (x *CdmaEvdoTower) GetChannel() int32 {
	if x != nil && x.Channel != nil {
		return *x.Channel
	}
	return 0
}

func (x *CdmaEvdoTower) GetPnoffset() int32 {
	if x != nil && x.Pnoffset != nil {
		return *x.Pnoffset
	}
	return 0
}

func (x *CdmaEvdoTower) GetLocation() *ALSLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

type LteCellTower struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mcc           *int32                 `protobuf:"varint,1,opt,name=mcc,proto3,oneof" json:"mcc,omitempty"`
	Mnc           *int32                 `protobuf:"varint,2,opt,name=mnc,proto3,oneof" json:"mnc,omitempty"`
	CellId        *int32                 `protobuf:"varint,3,opt,name=cell_id,json=cellId,proto3,oneof" json:"cell_id,omitempty"`
	TacId         *int32                 `protobuf:"varint,4,opt,name=tac_id,json=tacId,proto3,oneof" json:"tac_id,omitempty"`
	Location      *ALSLocation           `protobuf:"bytes,5,opt,name=location,proto3,oneof" json:"location,omitempty"`
	Uarfcn        *int32                 `protobuf:"varint,6,opt,name=uarfcn,proto3,oneof" json:"uarfcn,omitempty"`
	Pid           *int32                 `protobuf:"varint,7,opt,name=pid,proto3,oneof" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LteCellTower) Reset() {
	*x = LteCellTower{}
	mi := &file_apple_wps_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LteCellTower) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LteCellTower) ProtoMessage() {}

func (x *LteCellTower) ProtoReflect() protoreflect.Message {
	mi := &file_apple_wps_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LteCellTower.ProtoReflect.Descriptor instead.
func (*LteCellTower) Descriptor() ([]byte, []int) {
	return file_apple_wps_proto_rawDescGZIP(), []int{7}
}

func (x *LteCellTower) GetMcc() int32 {
	if x != nil && x.Mcc != nil {
		return *x.Mcc
	}
	return 0
}

func (x *LteCellTower) GetMnc() int32 {
	if x != nil && x.Mnc != nil {
		return *x.Mnc
	}
	return 0
}

func (x *LteCellTower) GetCellId() int32 {
	if x != nil && x.CellId != nil {
		return *x.CellId
	}
	return 0
}

func (x *LteCellTower) GetTacId() int32 {
	if x != nil && x.TacId != nil {
		return *x.TacId
	}
	return 0
}

func (x *LteCellTower) GetLocation() *ALSLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *LteCellTower) GetUarfcn() int32 {
	if x != nil && x.Uarfcn != nil {
		return *x.Uarfcn
	}
	return 0
}

func (x *LteCellTower) GetPid() int32 {
	if x != nil && x.Pid != nil {
		return *x.Pid
	}
	return 0
}

type ScdmaCellTower struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mcc           int32                  `protobuf:"varint,1,opt,name=mcc,proto3" json:"mcc,omitempty"`
	Mnc           int32                  `protobuf:"varint,2,opt,name=mnc,proto3" json:"mnc,omitempty"`
	CellId        int32                  `protobuf:"varint,3,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
	LacId         int32                  `protobuf:"varint,4,opt,name=lac_id,json=lacId,proto3" json:"lac_id,omitempty"`
	Location      *ALSLocation           `protobuf:"bytes,5,opt,name=location,proto3,oneof" json:"location,omitempty"`
	Arfcn         *int32                 `protobuf:"varint,11,opt,name=arfcn,proto3,oneof" json:"arfcn,omitempty"`
	Psc           *int32                 `protobuf:"varint,12,opt,name=psc,proto3,oneof" json:"psc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScdmaCellTower) Reset() {
	*x = ScdmaCellTower{}
	mi := &file_apple_wps_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScdmaCellTower) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScdmaCellTower) ProtoMessage() {}

func (x *ScdmaCellTower) ProtoReflect() protoreflect.Message {
	mi := &file_apple_wps_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScdmaCellTower.ProtoReflect.Descriptor instead.
func (*ScdmaCellTower) Descriptor() ([]byte, []int) {
	return file_apple_wps_proto_rawDescGZIP(), []int{8}
}

func (x *ScdmaCellTower) GetMcc() int32 {
	if x != nil {
		return x.Mcc
	}
	return 0
}

func (x *ScdmaCellTower) GetMnc() int32 {
	if x != nil {
		return x.Mnc
	}
	return 0
}

func (x *ScdmaCellTower) GetCellId() int32 {
	if x != nil {
		return x.CellId
	}
	return 0
}

func (x *ScdmaCellTower) GetLacId() int32 {
	if x != nil {
		return x.LacId
	}
	return 0
}

func (x *ScdmaCellTower) GetLocation() *ALSLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *ScdmaCellTower) GetArfcn() int32 {
	if x != nil && x.Arfcn != nil {
		return *x.Arfcn
	}
	return 0
}

func (x *ScdmaCellTower) GetPsc() int32 {
	if x != nil && x.Psc != nil {
		return *x.Psc
	}
	return 0
}

type Nr5GCellTower struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mcc           *int32                 `protobuf:"varint,1,opt,name=mcc,proto3,oneof" json:"mcc,omitempty"`
	Mnc           *int32                 `protobuf:"varint,2,opt,name=mnc,proto3,oneof" json:"mnc,omitempty"`
	CellId        *int32                 `protobuf:"varint,3,opt,name=cell_id,json=cellId,proto3,oneof" json:"cell_id,omitempty"`
	TacId         *int32                 `protobuf:"varint,4,opt,name=tac_id,json=tacId,proto3,oneof" json:"tac_id,omitempty"`
	Location      *ALSLocation           `protobuf:"bytes,5,opt,name=location,proto3,oneof" json:"location,omitempty"`
	Nrarfcn       *int32                 `protobuf:"varint,6,opt,name=nrarfcn,proto3,oneof" json:"nrarfcn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nr5GCellTower) Reset() {
	*x = Nr5GCellTower{}
	mi := &file_apple_wps_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nr5GCellTower) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nr5GCellTower) ProtoMessage() {}

func (x *Nr5GCellTower) ProtoReflect() protoreflect.Message {
	mi := &file_apple_wps_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nr5GCellTower.ProtoReflect.Descriptor instead.
func (*Nr5GCellTower) Descriptor() ([]byte, []int) {
	return file_apple_wps_proto_rawDescGZIP(), []int{9}
}

func (x *Nr5GCellTower) GetMcc() int32 {
	if x != nil && x.Mcc != nil {
		return *x.Mcc
	}
	return 0
}

func (x *Nr5GCellTower) GetMnc() int32 {
	if x != nil && x.Mnc != nil {
		return *x.Mnc
	}
	return 0
}

func (x *Nr5GCellTower) GetCellId() int32 {
	if x != nil && x.CellId != nil {
		return *x.CellId
	}
	return 0
}

func (x *Nr5GCellTower) GetTacId() int32 {
	if x != nil && x.TacId != nil {
		return *x.TacId
	}
	return 0
}

func (x *Nr5GCellTower) GetLocation() *ALSLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Nr5GCellTower) GetNrarfcn() int32 {
	if x != nil && x.Nrarfcn != nil {
		return *x.Nrarfcn
	}
	return 0
}

type ALSLocationRequest_ALSMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SoftwareBuild *string                `protobuf:"bytes,1,opt,name=software_build,json=softwareBuild,proto3,oneof" json:"software_build,omitempty"`
	ProductId     *string                `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3,oneof" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ALSLocationRequest_ALSMeta) Reset() {
	*x = ALSLocationRequest_ALSMeta{}
	mi := &file_apple_wps_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ALSLocationRequest_ALSMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ALSLocationRequest_ALSMeta) ProtoMessage() {}

func (x *ALSLocationRequest_ALSMeta) ProtoReflect() protoreflect.Message {
	mi := &file_apple_wps_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ALSLocationRequest_ALSMeta.ProtoReflect.Descriptor instead.
func (*ALSLocationRequest_ALSMeta) Descriptor() ([]byte, []int) {
	return file_apple_wps_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ALSLocationRequest_ALSMeta) GetSoftwareBuild() string {
	if x != nil && x.SoftwareBuild != nil {
		return *x.SoftwareBuild
	}
	return ""
}

func (x *ALSLocationRequest_ALSMeta) GetProductId() string {
	if x != nil && x.ProductId != nil {
		return *x.ProductId
	}
	return ""
}

var File_apple_wps_proto protoreflect.FileDescriptor

const file_apple_wps_proto_rawDesc = "" +
	"\n" +
	"\x0fapple_wps.proto\"\x9a\x0e\n" +
	"\x12ALSLocationRequest\x12+\n" +
	"\vcell_towers\x18\x01 \x03(\v2\n" +
	".CellTowerR\n" +
	"cellTowers\x12.\n" +
	"\fwireless_aps\x18\x02 \x03(\v2\v.WirelessAPR\vwirelessAps\x12B\n" +
	"\x1bnumber_of_surrounding_cells\x18\x03 \x01(\x05H\x00R\x18numberOfSurroundingCells\x88\x01\x01\x12B\n" +
	"\x1bnumber_of_surrounding_wifis\x18\x04 \x01(\x05H\x01R\x18numberOfSurroundingWifis\x88\x01\x01\x12'\n" +
	"\rapp_bundle_id\x18\x05 \x01(\tH\x02R\vappBundleId\x88\x01\x01\x128\n" +
	"\x10cdma_cell_towers\x18\x15 \x03(\v2\x0e.CdmaCellTowerR\x0ecdmaCellTowers\x128\n" +
	"\x10cdma_evdo_towers\x18\x16 \x03(\v2\x0e.CdmaEvdoTowerR\x0ecdmaEvdoTowers\x12K\n" +
	" number_of_surrounding_cdma_cells\x18\x17 \x01(\x05H\x03R\x1cnumberOfSurroundingCdmaCells\x88\x01\x01\x12T\n" +
	"%number_of_surrounding_cdma_evdo_cells\x18\x18 \x01(\x05H\x04R numberOfSurroundingCdmaEvdoCells\x88\x01\x01\x125\n" +
	"\x0flte_cell_towers\x18\x19 \x03(\v2\r.LteCellTowerR\rlteCellTowers\x12I\n" +
	"\x1fnumber_of_surrounding_lte_cells\x18\x1a \x01(\x05H\x05R\x1bnumberOfSurroundingLteCells\x88\x01\x01\x12;\n" +
	"\x11scdma_cell_towers\x18\x1b \x03(\v2\x0f.ScdmaCellTowerR\x0fscdmaCellTowers\x12M\n" +
	"!number_of_surrounding_scdma_cells\x18\x1c \x01(\x05H\x06R\x1dnumberOfSurroundingScdmaCells\x88\x01\x01\x128\n" +
	"\x10nr5g_cell_towers\x18\x1d \x03(\v2\x0e.Nr5GCellTowerR\x0enr5gCellTowers\x12K\n" +
	" number_of_surrounding_nr5g_cells\x18\x1e \x01(\x05H\aR\x1cnumberOfSurroundingNr5gCells\x88\x01\x01\x12R\n" +
	"\x16surrounding_wifi_bands\x18\x1f \x03(\x0e2\x1c.ALSLocationRequest.WifiBandR\x14surroundingWifiBands\x12Z\n" +
	"\x13wifi_altitude_scale\x18  \x01(\x0e2%.ALSLocationRequest.WifiAltitudeScaleH\bR\x11wifiAltitudeScale\x88\x01\x01\x124\n" +
	"\x04meta\x18! \x01(\v2\x1b.ALSLocationRequest.ALSMetaH\tR\x04meta\x88\x01\x01\x1a{\n" +
	"\aALSMeta\x12*\n" +
	"\x0esoftware_build\x18\x01 \x01(\tH\x00R\rsoftwareBuild\x88\x01\x01\x12\"\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tH\x01R\tproductId\x88\x01\x01B\x11\n" +
	"\x0f_software_buildB\r\n" +
	"\v_product_id\";\n" +
	"\bWifiBand\x12\x15\n" +
	"\x11WIFI_BAND_UNKNOWN\x10\x00\x12\r\n" +
	"\tK2DOT4GHZ\x10\x01\x12\t\n" +
	"\x05K5GHZ\x10\x02\"y\n" +
	"\x11WifiAltitudeScale\x12\x1f\n" +
	"\x1bWIFI_ALTITUDE_SCALE_UNKNOWN\x10\x00\x12\x1d\n" +
	"\x19KWIFI_ALTITUDE_SCALE_NONE\x10\x01\x12$\n" +
	" KWIFI_ALTITUDE_SCALE_10_TO_THE_2\x10\x02B\x1e\n" +
	"\x1c_number_of_surrounding_cellsB\x1e\n" +
	"\x1c_number_of_surrounding_wifisB\x10\n" +
	"\x0e_app_bundle_idB#\n" +
	"!_number_of_surrounding_cdma_cellsB(\n" +
	"&_number_of_surrounding_cdma_evdo_cellsB\"\n" +
	" _number_of_surrounding_lte_cellsB$\n" +
	"\"_number_of_surrounding_scdma_cellsB#\n" +
	"!_number_of_surrounding_nr5g_cellsB\x16\n" +
	"\x14_wifi_altitude_scaleB\a\n" +
	"\x05_meta\"\xda\x02\n" +
	"\x13ALSLocationResponse\x12+\n" +
	"\vcell_towers\x18\x01 \x03(\v2\n" +
	".CellTowerR\n" +
	"cellTowers\x12.\n" +
	"\fwireless_aps\x18\x02 \x03(\v2\v.WirelessAPR\vwirelessAps\x128\n" +
	"\x10cdma_cell_towers\x18\x15 \x03(\v2\x0e.CdmaCellTowerR\x0ecdmaCellTowers\x125\n" +
	"\x0flte_cell_towers\x18\x16 \x03(\v2\r.LteCellTowerR\rlteCellTowers\x12;\n" +
	"\x11scdma_cell_towers\x18\x17 \x03(\v2\x0f.ScdmaCellTowerR\x0fscdmaCellTowers\x128\n" +
	"\x10nr5g_cell_towers\x18\x18 \x03(\v2\x0e.Nr5GCellTowerR\x0enr5gCellTowers\"\xc3\x03\n" +
	"\vALSLocation\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x03R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x03R\tlongitude\x12\x1a\n" +
	"\baccuracy\x18\x03 \x01(\x05R\baccuracy\x12(\n" +
	"\rlocation_type\x18\x04 \x01(\x05H\x00R\flocationType\x88\x01\x01\x12\x1f\n" +
	"\baltitude\x18\x05 \x01(\x05H\x01R\baltitude\x88\x01\x01\x120\n" +
	"\x11vertical_accuracy\x18\x06 \x01(\x05H\x02R\x10verticalAccuracy\x88\x01\x01\x12#\n" +
	"\n" +
	"confidence\x18\a \x01(\x05H\x03R\n" +
	"confidence\x88\x01\x01\x12\x19\n" +
	"\x05score\x18\v \x01(\rH\x04R\x05score\x88\x01\x01\x12\x19\n" +
	"\x05reach\x18\f \x01(\x05H\x05R\x05reach\x88\x01\x01\x12 \n" +
	"\tinfo_mask\x18\r \x01(\rH\x06R\binfoMask\x88\x01\x01B\x10\n" +
	"\x0e_location_typeB\v\n" +
	"\t_altitudeB\x14\n" +
	"\x12_vertical_accuracyB\r\n" +
	"\v_confidenceB\b\n" +
	"\x06_scoreB\b\n" +
	"\x06_reachB\f\n" +
	"\n" +
	"_info_mask\"\xdf\x01\n" +
	"\tCellTower\x12\x10\n" +
	"\x03mcc\x18\x01 \x01(\x05R\x03mcc\x12\x10\n" +
	"\x03mnc\x18\x02 \x01(\x05R\x03mnc\x12\x17\n" +
	"\acell_id\x18\x03 \x01(\x05R\x06cellId\x12\x15\n" +
	"\x06lac_id\x18\x04 \x01(\x05R\x05lacId\x12-\n" +
	"\blocation\x18\x05 \x01(\v2\f.ALSLocationH\x00R\blocation\x88\x01\x01\x12\x19\n" +
	"\x05arcfn\x18\v \x01(\x05H\x01R\x05arcfn\x88\x01\x01\x12\x15\n" +
	"\x03psc\x18\f \x01(\x05H\x02R\x03psc\x88\x01\x01B\v\n" +
	"\t_locationB\b\n" +
	"\x06_arcfnB\x06\n" +
	"\x04_psc\"\xe5\x01\n" +
	"\n" +
	"WirelessAP\x12\x15\n" +
	"\x06mac_id\x18\x01 \x01(\tR\x05macId\x12-\n" +
	"\blocation\x18\x02 \x01(\v2\f.ALSLocationH\x00R\blocation\x88\x01\x01\x12\x1d\n" +
	"\achannel\x18\x15 \x01(\rH\x01R\achannel\x88\x01\x01\x12<\n" +
	"\x18num_zaxis_harvest_traces\x18\x16 \x01(\rH\x02R\x15numZaxisHarvestTraces\x88\x01\x01B\v\n" +
	"\t_locationB\n" +
	"\n" +
	"\b_channelB\x1b\n" +
	"\x19_num_zaxis_harvest_traces\"\xfc\x02\n" +
	"\rCdmaCellTower\x12\x15\n" +
	"\x03mcc\x18\x01 \x01(\x05H\x00R\x03mcc\x88\x01\x01\x12\x15\n" +
	"\x03sid\x18\x03 \x01(\x05H\x01R\x03sid\x88\x01\x01\x12\x15\n" +
	"\x03nid\x18\x04 \x01(\x05H\x02R\x03nid\x88\x01\x01\x12\x17\n" +
	"\x04bsid\x18\x05 \x01(\x05H\x03R\x04bsid\x88\x01\x01\x12-\n" +
	"\blocation\x18\x06 \x01(\v2\f.ALSLocationH\x04R\blocation\x88\x01\x01\x12\x1b\n" +
	"\x06zoneid\x18\a \x01(\x05H\x05R\x06zoneid\x88\x01\x01\x12!\n" +
	"\tbandclass\x18\b \x01(\x05H\x06R\tbandclass\x88\x01\x01\x12\x1d\n" +
	"\achannel\x18\t \x01(\x05H\aR\achannel\x88\x01\x01\x12\x1f\n" +
	"\bpnoffset\x18\n" +
	" \x01(\x05H\bR\bpnoffset\x88\x01\x01B\x06\n" +
	"\x04_mccB\x06\n" +
	"\x04_sidB\x06\n" +
	"\x04_nidB\a\n" +
	"\x05_bsidB\v\n" +
	"\t_locationB\t\n" +
	"\a_zoneidB\f\n" +
	"\n" +
	"_bandclassB\n" +
	"\n" +
	"\b_channelB\v\n" +
	"\t_pnoffset\"\xf1\x01\n" +
	"\rCdmaEvdoTower\x12\x1a\n" +
	"\bsectorid\x18\x01 \x01(\tR\bsectorid\x12!\n" +
	"\tbandclass\x18\x02 \x01(\x05H\x00R\tbandclass\x88\x01\x01\x12\x1d\n" +
	"\achannel\x18\x03 \x01(\x05H\x01R\achannel\x88\x01\x01\x12\x1f\n" +
	"\bpnoffset\x18\x04 \x01(\x05H\x02R\bpnoffset\x88\x01\x01\x12-\n" +
	"\blocation\x18\x05 \x01(\v2\f.ALSLocationH\x03R\blocation\x88\x01\x01B\f\n" +
	"\n" +
	"_bandclassB\n" +
	"\n" +
	"\b_channelB\v\n" +
	"\t_pnoffsetB\v\n" +
	"\t_location\"\xa0\x02\n" +
	"\fLteCellTower\x12\x15\n" +
	"\x03mcc\x18\x01 \x01(\x05H\x00R\x03mcc\x88\x01\x01\x12\x15\n" +
	"\x03mnc\x18\x02 \x01(\x05H\x01R\x03mnc\x88\x01\x01\x12\x1c\n" +
	"\acell_id\x18\x03 \x01(\x05H\x02R\x06cellId\x88\x01\x01\x12\x1a\n" +
	"\x06tac_id\x18\x04 \x01(\x05H\x03R\x05tacId\x88\x01\x01\x12-\n" +
	"\blocation\x18\x05 \x01(\v2\f.ALSLocationH\x04R\blocation\x88\x01\x01\x12\x1b\n" +
	"\x06uarfcn\x18\x06 \x01(\x05H\x05R\x06uarfcn\x88\x01\x01\x12\x15\n" +
	"\x03pid\x18\a \x01(\x05H\x06R\x03pid\x88\x01\x01B\x06\n" +
	"\x04_mccB\x06\n" +
	"\x04_mncB\n" +
	"\n" +
	"\b_cell_idB\t\n" +
	"\a_tac_idB\v\n" +
	"\t_locationB\t\n" +
	"\a_uarfcnB\x06\n" +
	"\x04_pid\"\xe4\x01\n" +
	"\x0eScdmaCellTower\x12\x10\n" +
	"\x03mcc\x18\x01 \x01(\x05R\x03mcc\x12\x10\n" +
	"\x03mnc\x18\x02 \x01(\x05R\x03mnc\x12\x17\n" +
	"\acell_id\x18\x03 \x01(\x05R\x06cellId\x12\x15\n" +
	"\x06lac_id\x18\x04 \x01(\x05R\x05lacId\x12-\n" +
	"\blocation\x18\x05 \x01(\v2\f.ALSLocationH\x00R\blocation\x88\x01\x01\x12\x19\n" +
	"\x05arfcn\x18\v \x01(\x05H\x01R\x05arfcn\x88\x01\x01\x12\x15\n" +
	"\x03psc\x18\f \x01(\x05H\x02R\x03psc\x88\x01\x01B\v\n" +
	"\t_locationB\b\n" +
	"\x06_arfcnB\x06\n" +
	"\x04_psc\"\x85\x02\n" +
	"\rNr5GCellTower\x12\x15\n" +
	"\x03mcc\x18\x01 \x01(\x05H\x00R\x03mcc\x88\x01\x01\x12\x15\n" +
	"\x03mnc\x18\x02 \x01(\x05H\x01R\x03mnc\x88\x01\x01\x12\x1c\n" +
	"\acell_id\x18\x03 \x01(\x05H\x02R\x06cellId\x88\x01\x01\x12\x1a\n" +
	"\x06tac_id\x18\x04 \x01(\x05H\x03R\x05tacId\x88\x01\x01\x12-\n" +
	"\blocation\x18\x05 \x01(\v2\f.ALSLocationH\x04R\blocation\x88\x01\x01\x12\x1d\n" +
	"\anrarfcn\x18\x06 \x01(\x05H\x05R\anrarfcn\x88\x01\x01B\x06\n" +
	"\x04_mccB\x06\n" +
	"\x04_mncB\n" +
	"\n" +
	"\b_cell_idB\t\n" +
	"\a_tac_idB\v\n" +
	"\t_locationB\n" +
	"\n" +
	"\b_nrarfcnB)Z'github.com/denysvitali/where-am-i/protob\x06proto3"

var (
	file_apple_wps_proto_rawDescOnce sync.Once
	file_apple_wps_proto_rawDescData []byte
)

func file_apple_wps_proto_rawDescGZIP() []byte {
	file_apple_wps_proto_rawDescOnce.Do(func() {
		file_apple_wps_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apple_wps_proto_rawDesc), len(file_apple_wps_proto_rawDesc)))
	})
	return file_apple_wps_proto_rawDescData
}

var file_apple_wps_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_apple_wps_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_apple_wps_proto_goTypes = []any{
	(ALSLocationRequest_WifiBand)(0),          // 0: ALSLocationRequest.WifiBand
	(ALSLocationRequest_WifiAltitudeScale)(0), // 1: ALSLocationRequest.WifiAltitudeScale
	(*ALSLocationRequest)(nil),                // 2: ALSLocationRequest
	(*ALSLocationResponse)(nil),               // 3: ALSLocationResponse
	(*ALSLocation)(nil),                       // 4: ALSLocation
	(*CellTower)(nil),                         // 5: CellTower
	(*WirelessAP)(nil),                        // 6: WirelessAP
	(*CdmaCellTower)(nil),                     // 7: CdmaCellTower
	(*CdmaEvdoTower)(nil),                     // 8: CdmaEvdoTower
	(*LteCellTower)(nil),                      // 9: LteCellTower
	(*ScdmaCellTower)(nil),                    // 10: ScdmaCellTower
	(*Nr5GCellTower)(nil),                     // 11: Nr5GCellTower
	(*ALSLocationRequest_ALSMeta)(nil),        // 12: ALSLocationRequest.ALSMeta
}
var file_apple_wps_proto_depIdxs = []int32{
	5,  // 0: ALSLocationRequest.cell_towers:type_name -> CellTower
	6,  // 1: ALSLocationRequest.wireless_aps:type_name -> WirelessAP
	7,  // 2: ALSLocationRequest.cdma_cell_towers:type_name -> CdmaCellTower
	8,  // 3: ALSLocationRequest.cdma_evdo_towers:type_name -> CdmaEvdoTower
	9,  // 4: ALSLocationRequest.lte_cell_towers:type_name -> LteCellTower
	10, // 5: ALSLocationRequest.scdma_cell_towers:type_name -> ScdmaCellTower
	11, // 6: ALSLocationRequest.nr5g_cell_towers:type_name -> Nr5GCellTower
	0,  // 7: ALSLocationRequest.surrounding_wifi_bands:type_name -> ALSLocationRequest.WifiBand
	1,  // 8: ALSLocationRequest.wifi_altitude_scale:type_name -> ALSLocationRequest.WifiAltitudeScale
	12, // 9: ALSLocationRequest.meta:type_name -> ALSLocationRequest.ALSMeta
	5,  // 10: ALSLocationResponse.cell_towers:type_name -> CellTower
	6,  // 11: ALSLocationResponse.wireless_aps:type_name -> WirelessAP
	7,  // 12: ALSLocationResponse.cdma_cell_towers:type_name -> CdmaCellTower
	9,  // 13: ALSLocationResponse.lte_cell_towers:type_name -> LteCellTower
	10, // 14: ALSLocationResponse.scdma_cell_towers:type_name -> ScdmaCellTower
	11, // 15: ALSLocationResponse.nr5g_cell_towers:type_name -> Nr5GCellTower
	4,  // 16: CellTower.location:type_name -> ALSLocation
	4,  // 17: WirelessAP.location:type_name -> ALSLocation
	4,  // 18: CdmaCellTower.location:type_name -> ALSLocation
	4,  // 19: CdmaEvdoTower.location:type_name -> ALSLocation
	4,  // 20: LteCellTower.location:type_name -> ALSLocation
	4,  // 21: ScdmaCellTower.location:type_name -> ALSLocation
	4,  // 22: Nr5GCellTower.location:type_name -> ALSLocation
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_apple_wps_proto_init() }
func file_apple_wps_proto_init() {
	if File_apple_wps_proto != nil {
		return
	}
	file_apple_wps_proto_msgTypes[0].OneofWrappers = []any{}
	file_apple_wps_proto_msgTypes[2].OneofWrappers = []any{}
	file_apple_wps_proto_msgTypes[3].OneofWrappers = []any{}
	file_apple_wps_proto_msgTypes[4].OneofWrappers = []any{}
	file_apple_wps_proto_msgTypes[5].OneofWrappers = []any{}
	file_apple_wps_proto_msgTypes[6].OneofWrappers = []any{}
	file_apple_wps_proto_msgTypes[7].OneofWrappers = []any{}
	file_apple_wps_proto_msgTypes[8].OneofWrappers = []any{}
	file_apple_wps_proto_msgTypes[9].OneofWrappers = []any{}
	file_apple_wps_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apple_wps_proto_rawDesc), len(file_apple_wps_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apple_wps_proto_goTypes,
		DependencyIndexes: file_apple_wps_proto_depIdxs,
		EnumInfos:         file_apple_wps_proto_enumTypes,
		MessageInfos:      file_apple_wps_proto_msgTypes,
	}.Build()
	File_apple_wps_proto = out.File
	file_apple_wps_proto_goTypes = nil
	file_apple_wps_proto_depIdxs = nil
}
