run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number
      path: stdout
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - decorder
    - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - gosmopolitan
    - govet
    - grouper
    - importas
    - ineffassign
    - interfacebloat
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagalign
    - tagliatelle
    - tenv
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
    - zerologlint

linters-settings:
  cyclop:
    max-complexity: 15
  
  dupl:
    threshold: 100
  
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  funlen:
    lines: 100
    statements: 50
  
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/denysvitali/where-am-i)
  
  gocognit:
    min-complexity: 15
  
  goconst:
    min-len: 3
    min-occurrences: 3
  
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  
  gocyclo:
    min-complexity: 15
  
  godot:
    scope: declarations
    capital: true
  
  gofumpt:
    lang-version: "1.24"
    extra-rules: true
  
  goimports:
    local-prefixes: github.com/denysvitali/where-am-i
  
  gosec:
    severity: medium
    confidence: medium
  
  lll:
    line-length: 120
  
  misspell:
    locale: US
  
  nakedret:
    max-func-lines: 30
  
  nestif:
    min-complexity: 4
  
  revive:
    rules:
      - name: unexported-return
      - name: unused-parameter
      - name: var-declaration
      - name: package-comments
      - name: exported
  
  stylecheck:
    checks: ["all"]
  
  varnamelen:
    min-name-length: 2
    ignore-names:
      - err
      - ok
      - id
      - ip
      - db
      - tx
      - wg
      - mu
    ignore-decls:
      - c echo.Context
      - t testing.T
      - f *os.File
      - w http.ResponseWriter
      - r *http.Request

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - gochecknoglobals
        - gocognit
        - goconst
        - gocyclo
        - lll
        - varnamelen
        - wrapcheck
    
    - path: cmd/
      linters:
        - gochecknoinits
    
    - path: internal/proto/
      linters:
        - all
  
  exclude-dirs:
    - vendor
  
  exclude-files:
    - ".*\\.pb\\.go$"
  
  max-issues-per-linter: 0
  max-same-issues: 0
