# Where Am I Configuration File
# Copy this to ~/.config/where-am-i/config.yaml or specify with --config flag

server:
  # Apple WPS server URL
  url: "https://gs-loc.apple.com/clls/wloc"
  # Alternative: GrapheneOS proxy
  # url: "https://gs-loc.apple.grapheneos.org/clls/wloc"
  
  # Timeouts in milliseconds
  connect_timeout: 10000
  read_timeout: 10000
  
  # Enforce modern TLS (TLS 1.3)
  enforce_modern_tls: false

throttle:
  # Cooldown period after throttling is triggered
  cooldown: 10s
  # Number of results that triggers throttling
  trigger_result_count: 17
  # Max additional results when throttled
  throttled_additional_results: 8
  # Max additional results normally
  max_additional_results: 100

request:
  # Maximum number of networks to request at once
  max_request_networks: 40
  
  # Request headers and metadata
  user_agent: "locationd/2960.0.57 CFNetwork/3826.500.111.1.1 Darwin/24.4.0"
  locale: "en-US_US"
  identifier: "com.apple.locationd"
  version: "15.4.24E248"
  software_build: "macOS15.4/24E248"
  product_id: "arm64"
